# Generated by Django 2.0.5 on 2018-05-10 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardinfo',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='cards.Card'),
        ),
    ]
