# Generated by Django 2.0.5 on 2018-05-10 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20180510_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardhistory',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cards.Card', verbose_name='银行卡'),
        ),
    ]
